
# https://github.com/michalswi/github-actions

name: Pipeline for Azure Functions

on:
  [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Build
      run: make build

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: simplewebs
        path: ./simplewebs

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: simplewebs

    # - name: Log in to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Run Azure Functions
    #   uses: Azure/functions-action@v1
    #   with:
    #     app-name: ${{ secrets.FUNCTION_APP }}
    #     package: ${{ github.workspace }}
